spring.data.mongodb.uri=mongodb+srv://shakyaneetesh2_db_user:hn8MhTm9hxxblPBt@cluster0.a4y0qwo.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true